### ISSUE TITLE
react-scripts: not found

### ISSUE THREAD

**Issue by Smarty-pro** [jakkra/Rover-Mission-Control#1]
When I run the code, I have this error
`> Rover-MCT@0.1.0 start /home/alpha/Rover-Mission-Control
> react-scripts start

sh: 1: react-scripts: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! Rover-MCT@0.1.0 start: `react-scripts start`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the Rover-MCT@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
`

**Comment by Smarty-pro** [comment]
Should I run npm install before ?

**Comment by Smarty-pro** [comment]
I still have the issue

**Comment by jakkra** [comment]
```
npm install
npm start
```
Works for me on a computer I have not run this projct on before. 
Make sure you have latest node version, I have `v12.18.2`
